### ISSUE TITLE
Using Google API with Calendar

### ISSUE THREAD

**Issue by jward8** [monica22schmidt/Culture-Project#4]
We might have a little bit of a problem when making a general public calendar. Apparently, from what David and Justin told me, the Google Calendar API doesn't really allow for just a public calendar. This might come up as an issue since we'd need one for the entire site to use. Obviously we can talk more in detail about everything next big meeting, but here is our proposed solution to the issue. 

https://docs.google.com/document/d/1lYod7b4e_98EwtYdXbTqLmsDyVyZUvX9fu8PhLr-yAk/edit

**Comment by klmui** [comment]
Monica suggested that we use a new API. I looked into the FullCalendar API and have implemented it. It has the functions we have are looking for. We should talk about it soon.
